on: push
name: 🚀 Deploy Nimbus Dashboard on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.6
      with:
        server: ftp.driftnimbus.com
        username: dev@driftnimbus.com
        password: ${{ secrets.PASSWORD }}
        server-dir: /dashboard/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.env
          **/vendor/**
          **/*.code-workspace
